### PR TITLE
Support for Delete

### PR DESCRIPTION
**Pull request by cincuranet**
~This is stacked on top of #28.~

### CODE REVIEW

**Comment by cincuranet** [comment]
@atroyn I just want to verify that I understand the docs correctly (specifically the _A promise that resolves to the IDs of the deleted items._ from [here](https://docs.trychroma.com/reference/js-collection#delete)). The failing tests here are doing delete of non-existing ID, but it looks like Chroma returns that ID even though it does not exist. Basically in pseudo code:

1. `Add(ids: [id1])`
2. `Delete(ids: [id1, id2])` (no `where`, no `where_document`)

Based on the above text, I assume the response from server will contain only `id1` (because `id2` does not exist). But the response contains both `id1` and `id2`. In _Chroma_'s log I see `Delete of nonexisting embedding ID: ...`. Quick look through issue in https://github.com/chroma-core/chroma repo does not show this as known issue.

Is this expected behavior (and my assumption is incorrect) or is it a bug?

**Comment by atroyn** [comment]
@cincuranet this looks like a bug; could you open an issue against Chroma and tag me? Cheers, Anton.

**Comment by cincuranet** [comment]
Done: https://github.com/chroma-core/chroma/issues/2841. I'll disable that asserts for now.

**Comment by cincuranet** [comment]
@ssone95 This is ready for review.

**Comment by ssone95** [comment]
> @ssone95 This is ready for review.

Already on it 🙂

**Pull request merged**
